name: file_picker_cross
description: Select, open, choose or pick documents, images videos or other files on Android, iOS, the desktop and the web for reading, writing, use as String, byte list or HTTP uploads.
version: 3.0.2
homepage: https://gitlab.com/testapp-system/file_picker_cross
respsitory: https://gitlab.com/testapp-system/file_picker_cross.git
issue_tracker: https://gitlab.com/testapp-system/file_picker_cross/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^1.6.3
  http: ^0.12.0+4
  http_parser: ^3.1.3
  file_chooser: ^0.1.4
#    git:
#      url: git://github.com/google/flutter-desktop-embedding.git
#      ref: master
#      path: plugins/file_chooser/

dev_dependencies:
  flutter_test:
    sdk: flutter
